### ISSUE TITLE
Error in changelogger new

### ISSUE THREAD

**Issue by djschilling** [churchtools/changelogger#14]
When calling `./bin/changelogger new` i get the following git error:

`error: Unbekannte Option: `show-current'`

**Comment by obstschale** [comment]
Did you try using `changelogger` in a project without git? The command  `git branch --show-current` is currently used to determine the branch name for the file name.

Workaround: `changelogger new -i <filename>`.

I think, I will change the behaviour and not use git at all to avoid the necessity of git.

**Comment by djschilling** [comment]
no i was in a project folder with git.

**Comment by obstschale** [comment]
Ok, weird. Whatsoever, like I said, I will remove the git command from the project with the next release and move to timestamps or something else.
