### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by MaPePeR** [churchtools/changelogger#49]
Because of the php requirement in `composer.json` this tool cannot be used in PHP8 at the moment:
```
  "require": {
    "php": "^7.2.5",
    "ext-json": "*"
},
```

I cloned the repository, changed the `php` requirement to `^7.2.5|^8.0`, did a `composer update` and ran the tests using `composer test` and all of them were successful. The `./changelogger` script also seems to work fine, so I assume the `composer.json` is the only problem.

I could trick my project to install changelogger as a dependency, but because of the runtime checks the program refuses to run on PHP8.

Sadly I don't know how to properly build this project, so I'm not comfortable doing a pull request.

**Comment by obstschale** [comment]
I will take a look and make it php8 compatible

**Comment by strausmann** [comment]
+1

**Comment by obstschale** [comment]
Next version will support php7.4, 8.0
